types:
  - test
  - package

variables:
  XCSBOT: "fc03b092ecd597b3488984a34d029eec"
  XCSBOT_IOS: "8398cace692793b0b9d5ab1fe0964301"

  GITLAB_PROJECT_ID: "9"
  FRAMEWORK_NAME: "NaOH"

testMac:
  type: test
  script:
    - "/Applications/CaveJohnson.app/Contents/MacOS/CaveJohnsonCLI forceGitLabBranch --branchName CaveJohnsonAuto --hostname code.sealedabstract.com --projectID $GITLAB_PROJECT_ID"
    - "sleep 1" 
    - "XCSBUILDNO=`/Applications/CaveJohnson.app/Contents/MacOS/CaveJohnsonCLI xcsIntegrateNow --botID $XCSBOT --hostname localhost --sslPolicy localhost`"
    - "echo XCS BUILDNO $XCSBUILDNO"
    - "/Applications/CaveJohnson.app/Contents/MacOS/CaveJohnsonCLI waitForIntegration --hostname localhost --botID $XCSBOT --sslPolicy localhost --buildNumber $XCSBUILDNO"
    - "/Applications/CaveJohnson.app/Contents/MacOS/CaveJohnsonCLI xcsStatusToShell --hostname localhost --botID $XCSBOT --sslPolicy localhost --buildNumber $XCSBUILDNO"
  only:
    - master
  tags:
    - xc7

testiOS:
  type: test
  script:
    - "/Applications/CaveJohnson.app/Contents/MacOS/CaveJohnsonCLI forceGitLabBranch --branchName CaveJohnsonAuto --hostname code.sealedabstract.com --projectID $GITLAB_PROJECT_ID"
    - "sleep 1" 
    - "XCSBUILDNO=`/Applications/CaveJohnson.app/Contents/MacOS/CaveJohnsonCLI xcsIntegrateNow --botID $XCSBOT_IOS --hostname localhost --sslPolicy localhost`"
    - "echo XCS BUILDNO $XCSBUILDNO"
    - "/Applications/CaveJohnson.app/Contents/MacOS/CaveJohnsonCLI waitForIntegration --hostname localhost --botID $XCSBOT_IOS --sslPolicy localhost --buildNumber $XCSBUILDNO"
    - "/Applications/CaveJohnson.app/Contents/MacOS/CaveJohnsonCLI xcsStatusToShell --hostname localhost --botID $XCSBOT_IOS --sslPolicy localhost --buildNumber $XCSBUILDNO"
  only:
    - master
  tags:
    - xc7

archiveiOS:
   type: package
   script:
      - "CJ=/Applications/CaveJohnson.app/Contents/MacOS/CaveJohnsonCLI"
      - "CARTHAGE=/usr/local/bin/carthage"
      - "$CJ setVersion --infoPlistPath $FRAMEWORK_NAME/Info.plist --version ${CI_BUILD_ID}"
      - "$CARTHAGE build --no-skip-current --platform ios"
      - "$CARTHAGE archive $FRAMEWORK_NAME"

      - "ZIPFILE=$($CJ getNameVersionString --infoPlistPath $FRAMEWORK_NAME/Info.plist --productName $FRAMEWORK_NAME)-dev-${CI_BUILD_ID}.zip"
      - "rm -rf /tmp/$FRAMEWORK_NAME/"
      - "mkdir -p /tmp/$FRAMEWORK_NAME"
      - "mv $FRAMEWORK_NAME.framework.zip /tmp/$FRAMEWORK_NAME/$ZIPFILE"
   only:
    - master

   artifacts:
      paths:
      - /tmp/NaOH/

archiveMac:
   type: package
   script:
      - "CJ=/Applications/CaveJohnson.app/Contents/MacOS/CaveJohnsonCLI"
      - "CARTHAGE=/usr/local/bin/carthage"
      - "$CJ setVersion --infoPlistPath $FRAMEWORK_NAME/Info.plist --version ${CI_BUILD_ID}"
      - "$CARTHAGE build --no-skip-current"
      - "$CARTHAGE archive $FRAMEWORK_NAME --platform osx"

      - "ZIPFILE=$($CJ getNameVersionString --infoPlistPath $FRAMEWORK_NAME/Info.plist --productName $FRAMEWORK_NAME)-dev-${CI_BUILD_ID}.zip"
      - "rm -rf /tmp/$FRAMEWORK_NAME/"
      - "mkdir -p /tmp/$FRAMEWORK_NAME"
      - "mv $FRAMEWORK_NAME.framework.zip /tmp/$FRAMEWORK_NAME/$ZIPFILE"
   only:
    - master

   artifacts:
      paths:
      - /tmp/NaOH/