types:
  - test
  - package

variables:
  XCSBOT: "fc03b092ecd597b3488984a34d029eec"
  GITLAB_PROJECT_ID: "9"

xcs:
  type: test
  script:
    - "/Applications/CaveJohnson.app/Contents/MacOS/CaveJohnsonCLI forceGitLabBranch --branchName CaveJohnsonAuto --hostname code.sealedabstract.com --projectID $GITLAB_PROJECT_ID"
    - "sleep 1" 
    - "XCSBUILDNO=`/Applications/CaveJohnson.app/Contents/MacOS/CaveJohnsonCLI xcsIntegrateNow --botID $XCSBOT --hostname localhost --sslPolicy localhost`"
    - "/Applications/CaveJohnson.app/Contents/MacOS/CaveJohnsonCLI waitForIntegration --hostname localhost --botID $XCSBOT --sslPolicy localhost --buildNumber $XCSBUILDNO"
    - "/Applications/CaveJohnson.app/Contents/MacOS/CaveJohnsonCLI xcsStatusToShell --hostname localhost --botID $XCSBOT --sslPolicy localhost --buildNumber $XCSBUILDNO"
  only:
    - master
  tags:
    - xc7

archive:
   type: package
   script:
      - "ls"
      - "CJ=/Applications/CaveJohnson.app/Contents/MacOS/CaveJohnsonCLI"
      - "CARTHAGE=/usr/local/bin/carthage"
      - "$CJ setVersion --infoPlistPath NaOH/NaOH/Info.plist --version ${CI_BUILD_ID}"
      - "$CARTHAGE build --no-skip-current"
      - "$CARTHAGE archive NaOH"

      - "ZIPFILE=$($CJ getNameVersionString --infoPlistPath NaOH/NaOH/Info.plist --productName NaOH)-dev-${CI_BUILD_ID}.zip"
      - "rm -rf /tmp/NaOH/"
      - "mkdir -p /tmp/NaOH"
      - "mv NaOH.framework.zip /tmp/NaOH/$ZIPFILE"

   artifacts:
      paths:
      - /tmp/NaOH/